const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const source = fs.readFileSync(require('node:path').join(__dirname, '../src/lib/activity-display.ts'), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
const context = { exports: {}, Date };
vm.runInNewContext(compiled, context);
const { activityDateLabel, activityStatusLabel, latestActivities } = context.exports;
assert.equal(activityStatusLabel(null).status, 'ไม่ระบุ');
assert.equal(activityStatusLabel(' ').status, 'ไม่ระบุ');
assert.equal(activityStatusLabel('กำลังดำเนินการ').statusColor, 'badge-blue');
assert.equal(activityStatusLabel('ยกเลิก').status, 'ยกเลิก');
assert.equal(activityStatusLabel('ยกเลิก').statusColor, 'badge-gray');
assert.equal(activityDateLabel(null), 'ไม่ระบุวันที่');
assert.equal(activityDateLabel('2026-02-30'), 'ไม่ระบุวันที่');
assert.equal(activityDateLabel('2026-10-02', 'event', 'day'), '2 ต.ค. 2569');
assert.equal(activityDateLabel('2026-10-02', 'announcement', 'day'), 'วันประกาศ: 2 ต.ค. 2569');
assert.equal(activityDateLabel('2026-10-01', 'application_close', 'month'), 'วันปิดรับสมัคร: ต.ค. 2569');
assert.equal(activityDateLabel('2026-01-01', 'event', 'year'), '2569');
assert.equal(activityDateLabel('2026-10-02', 'event', 'approximate'), 'ประมาณ 2 ต.ค. 2569');
const input = [{id: 1, startDate: null}, {id: 2, startDate: '2025-01-01'}, {id: 3, startDate: '2026-01-01'}, {id: 4, startDate: '2026-01-01'}];
assert.deepEqual(Array.from(latestActivities(input), x => x.id), [4, 3, 2, 1]);
assert.deepEqual(input.map(x => x.id), [1, 2, 3, 4]);
assert.deepEqual(Array.from(latestActivities(input, 2), x => x.id), [4, 3]);
console.log('PASS: authoritative status, date kind/precision, calendar dates, stable latest ordering');
